# Generated by Django 4.2.9 on 2024-03-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutapp', '0002_aboutapp_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('about_me', models.CharField(max_length=200)),
                ('why_us', models.CharField(max_length=200)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
