# Generated by Django 4.2.9 on 2024-02-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['added_on']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-posting_date']},
        ),
    ]
